# Generated by Django 5.0.4 on 2024-04-07 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
